export const FETCH_ROUNDS = 'FETCH_ROUNDS';
export const FETCH_TEAMS = 'FETCH_TEAMS';
export const FETCH_TEAM = 'FETCH_TEAM';
export const FETCH_PLAYERS = 'FETCH_PLAYERS';
export const FETCH_PLAYER = 'FETCH_PLAYER';
export const FETCH_LEAGUE = 'FETCH_LEAGUE';
export const FETCH_DRAFT_PICKS = 'FETCH_DRAFT_PICKS';
