export const FETCH_ROUNDS = 'FETCH_ROUNDS';
export const FETCH_TEAMS = 'FETCH_TEAMS';
export const FETCH_TEAM = 'FETCH_TEAM';

export const FETCH_PLAYERS = 'FETCH_PLAYERS';
export const FETCH_PLAYER = 'FETCH_PLAYER';
export const FETCH_LEAGUE = 'FETCH_LEAGUE';

export const FETCH_DRAFT_PICKS = 'FETCH_DRAFT_PICKS';
export const UPDATE_DRAFT_PICK = 'UPDATE_DRAFT_PICK';
export const CREATE_DRAFT_PICKS = 'CREATE_DRAFT_PICKS';

export const FETCH_FPL_TEAMS = 'FETCH_FPL_TEAMS';
export const FETCH_FPL_TEAM = 'FETCH_FPL_TEAM';

export const FETCH_FPL_TEAM_LISTS = 'FETCH_FPL_TEAM_LISTS';
export const FETCH_FPL_TEAM_LIST = 'FETCH_FPL_TEAM_LIST';
export const UPDATE_FPL_TEAM_LIST = 'UPDATE_FPL_TEAM_LIST';

export const TRADE_PLAYERS = 'TRADE_PLAYERS';

export const CREATE_WAIVER_PICK = 'CREATE_WAIVER_PICK';
export const FETCH_WAIVER_PICKS = 'FETCH_WAIVER_PICKS';
export const UPDATE_WAIVER_PICK_ORDER = 'UPDATE_WAIVER_PICK_ORDER';
export const DELETE_WAIVER_PICK = 'DELETE_WAIVER_PICK';

export const FETCH_POSITIONS = 'FETCH_POSITIONS';

export const FETCH_MINI_DRAFT_PICKS = 'FETCH_MINI_DRAFT_PICKS';
export const CREATE_MINI_DRAFT_PICK = 'CREATE_MINI_DRAFT_PICK';
export const PASS_MINI_DRAFT_PICK = 'PASS_MINI_DRAFT_PICK';

export const SHOW_ERRORS = 'SHOW_ERRORS';

export const INTER_TEAM_TRADE_GROUPS = 'INTER_TEAM_TRADE_GROUPS';
export const NEW_INTER_TEAM_TRADE_GROUP = 'NEW_INTER_TEAM_TRADE_GROUP';
export const CREATE_INTER_TEAM_TRADE_GROUP = 'CREATE_INTER_TEAM_TRADE_GROUP';
export const INTER_TEAM_TRADE_GROUP = 'INTER_TEAM_TRADE_GROUP';
