RecurringActivePlayerFixtureHistoriesWorker:
  cron: '*/3 0-9,23 * * *'
  class: 'RecurringActivePlayerFixtureHistoriesWorker'

RecurringPlayerPastHistoryWorker:
  cron: '0 12 * * 5'
  class: 'RecurringPlayerPastHistoryWorker'

RecurringPlayerWorker:
  cron: '*/3 0-9,23 * * *'
  class: 'RecurringPlayerWorker'

RecurringPositionWorker:
  cron: '00 12 * * 5'
  class: 'RecurringPositionWorker'

RecurringRoundWorker:
  cron: '0 */6 * * *'
  class: 'RecurringRoundWorker'

RecurringTeamWorker:
  cron: '00-59/3 0-9,23 * * *'
  class: 'RecurringTeamWorker'
